# Generated by Django 6.1 on 2026-08-16 22:58

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models

import api_auth.models.manager
import api_utils.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apicore", "0002_immutable_unaccent"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("email", models.EmailField(db_default="", default="", max_length=254)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=False, default=False)),
                ("is_staff", models.BooleanField(db_default=False, default=False)),
                ("is_superuser", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "ordering": ("username",),
                "abstract": False,
            },
            managers=[
                ("objects", api_auth.models.manager.ApiUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApiUserGroups",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserGroupsEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserPermissions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserPermissionsEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("email", models.EmailField(db_default="", default="", max_length=254)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=False, default=False)),
                ("is_staff", models.BooleanField(db_default=False, default=False)),
                ("is_superuser", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        condition=models.Q(("pgh_context__isnull", False)),
                        fields=["pgh_context"],
                        name="gin_apiuserevent_ctx_path",
                        opclasses=["jsonb_path_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            expression=django.db.models.fields.json.KeyTextTransform(
                                "url", "pgh_context"
                            ),
                            name="gin_trgm_ops",
                        ),
                        condition=models.Q(("pgh_context__isnull", False)),
                        name="gin_apiuserevent_ctx_url",
                    ),
                    models.Index(
                        django.db.models.fields.json.KeyTransform(
                            "id",
                            django.db.models.fields.json.KeyTransform(
                                "user", "pgh_context"
                            ),
                        ),
                        condition=models.Q(
                            ("pgh_context__has_key", "user"),
                            ("pgh_context__isnull", False),
                        ),
                        name="idx_apiuserevent_ctx_userid",
                    ),
                    models.Index(
                        fields=["pgh_created_at"], name="idx_apiuserevent_pghcreatedat"
                    ),
                    models.Index(
                        fields=["pgh_label"], name="idx_apiuserevent_pghlabel"
                    ),
                    models.Index(fields=["id"], name="idx_apiuserevent_id"),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="644c006f1fe0ddb5cedec536a0ace636c9df8f2f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_203fb",
                    table="apiauth_apiuserevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="apiusergroups",
            name="api_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiusergroups",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="groups",
            field=models.ManyToManyField(
                related_name="users", through="apiauth.ApiUserGroups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="apiusergroupsevent",
            name="api_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiusergroupsevent",
            name="group",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissions",
            name="api_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissions",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="permissions",
            field=models.ManyToManyField(
                related_name="users",
                through="apiauth.ApiUserPermissions",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissionsevent",
            name="api_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissionsevent",
            name="permission",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiusergroups",
            constraint=models.UniqueConstraint(
                fields=("api_user", "group"), name="unq_apiusergroups_apiuser_group"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="8d95991809115c54a7b519b7e98aa7febdbe92e3",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_7ef7a",
                    table="apiauth_apiusergroups",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="fa7af5056682135b7ddbd51e16b38fa53a862534",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_7c925",
                    table="apiauth_apiusergroups",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."api_user_id", OLD."group_id", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="4e6eb9224e427b0042cd35d9b619e5b396df5dab",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_ce6ef",
                    table="apiauth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."group_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="40fd94b294b4e71d98e7e3404d72c8f1e26a5aa4",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_40cf9",
                    table="apiauth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."group_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="39ee1e7b9e50a222d0dad7b16a0a8ea50164269b",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_4654e",
                    table="apiauth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiusergroupsevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiusergroupsevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiusergroupsevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_apiusergroupsevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiusergroupsevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(fields=["id"], name="idx_apiusergroupsevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroupsevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="5a4ebbe98b68a2a6fe23483e3e8c0aaadf1a9561",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_aac4c",
                    table="apiauth_apiusergroupsevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuserpermissions",
            constraint=models.UniqueConstraint(
                fields=("api_user", "permission"),
                name="unq_apiuserpermissions_apiuser_permission",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="8d1ea7a3588dc8ec266f7052eb99df2ed14f3ebd",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_7ce24",
                    table="apiauth_apiuserpermissions",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="d016fa06587165ad1b2c8ae0c40c8f82022d5f3c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_b42a6",
                    table="apiauth_apiuserpermissions",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."api_user_id", OLD."id", OLD."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="44733d851d5ec32a87f5badcb42e218f169996ab",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_007bc",
                    table="apiauth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."id", NEW."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="52c7be5219d87218dd3689a6ba77148ca8d7ca3a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_62eb3",
                    table="apiauth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."id", NEW."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="7fb4f4c82e61b6824f64c4af254d8047c7548fe0",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_30522",
                    table="apiauth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("username")
                    ),
                    name="gin_trgm_ops",
                ),
                name="gin_apiuser_username",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("email")
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("email__len__gt", 0)),
                name="gin_apiuser_email",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(fields=["created_at"], name="idx_apiuser_createdat"),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(fields=["is_active"], name="idx_apiuser_isactive"),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email__len__gt", 0)),
                name="unq_apiuser_email",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="2ae7cb711146e6862bbde182b6381641b6bfe595",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_60eb8",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="86d3d19ed637a35dc1f962d3c427fc101c73a76b",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_f50e9",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuser_protect_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot insert rows from % table', TG_TABLE_NAME;",
                    hash="bc386f0ec0fa89f0ebc42af45bae93b956745ff6",
                    operation="INSERT",
                    pgid="pgtrigger_trg_apiuser_protect_insert_79be2",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuser_readonly_createdat",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="ce8f52839c9569096c5ae58f46dc3d0a53cc4763",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiuser_readonly_createdat_9b152",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuser_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "apiauth_apiuser" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="e2f289ac0ac26d27aecbe36021172c0981b4ef36",
                    operation="DELETE",
                    pgid="pgtrigger_trg_apiuser_softdelete_isactive_3a12d",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserevent" ("created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "username") VALUES (OLD."created_at", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", OLD."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."username"); RETURN NULL;',
                    hash="0ce78df7029dc12fb09a689bab306e8b4ac77b76",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_70bb8",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserevent" ("created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "username") VALUES (NEW."created_at", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."username"); RETURN NULL;',
                    hash="e21910593b4647c31bfad7ba59c4ccf3d59c9174",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_bf524",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apiuserevent" ("created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "username") VALUES (NEW."created_at", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."username"); RETURN NULL;',
                    hash="4abeed4608946102c78c11ee0405c0ebd133a078",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_819c8",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiuserpermissionsevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiuserpermissionsevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiuserpermissionsevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_apiuserpermissionsevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiuserpermissionsevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(fields=["id"], name="idx_apiuserpermissionsevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissionsevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="a74aee8363b6f282333a3fae5f243cde8e5f1ee1",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_e47c0",
                    table="apiauth_apiuserpermissionsevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
