services:
  migrate:
    build:
      cache_from:
        - type=gha,scope=rudiapi-prod

  rudiapi-prod:
    build:
      cache_from:
        - type=gha,scope=rudiapi-prod
      cache_to:
        - type=gha,mode=max,scope=rudiapi-prod
