# Generated by Django 6.1 on 2026-08-20 21:42

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
import django.db.models.functions.json
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Motivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                (
                    "etiqueta",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("ambito", models.CharField(max_length=30)),
                (
                    "visibilidad",
                    models.CharField(
                        db_default="administracion",
                        default="administracion",
                        max_length=20,
                    ),
                ),
                (
                    "require_descripcion",
                    models.BooleanField(db_default=False, default=False),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                ("descripcion", models.TextField(db_default="", default="")),
                ("grupo", models.CharField(max_length=20)),
                ("tipo", models.CharField(max_length=10)),
                ("valor", models.JSONField()),
                (
                    "restricciones",
                    models.JSONField(
                        db_default=django.db.models.functions.json.JSONObject(),
                        default=dict,
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlantillaMensaje",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                (
                    "etiqueta",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("asunto", models.CharField(max_length=200)),
                ("cuerpo", models.TextField()),
                (
                    "variables",
                    models.JSONField(
                        db_default=django.db.models.functions.json.JSONArray(),
                        default=list,
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RolParticipacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                (
                    "etiqueta",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("descripcion", models.TextField(db_default="", default="")),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoActividad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                (
                    "etiqueta",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("descripcion", models.TextField(db_default="", default="")),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoMentor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                (
                    "etiqueta",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("descripcion", models.TextField(db_default="", default="")),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoReconocimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                (
                    "etiqueta",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("descripcion", models.TextField(db_default="", default="")),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AreaExperiencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                (
                    "etiqueta",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("descripcion", models.TextField(db_default="", default="")),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="idx_areaexperiencia_createdat"
                    ),
                    models.Index(
                        fields=["updated_at"], name="idx_areaexperiencia_updatedat"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q((
                            "codigo__regex",
                            "^[\\p{L}\\d_-]+(\\.[\\p{L}\\d_-]+)*$",
                        )),
                        name="chk_areaexperiencia_codigo_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("descripcion__len__lte", 300)),
                        name="chk_areaexperiencia_descripcion",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("codigo"),
                        name="unq_areaexperiencia_codigo",
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="areaexperiencia",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="7600227dfe13e63f48531184266f1febe97347d9",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_e1098",
                    table="rudicatalogos_areaexperiencia",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="areaexperiencia",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="16aa667685b5c384eb0bab08b03264f98ec1da4b",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_26303",
                    table="rudicatalogos_areaexperiencia",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="areaexperiencia",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="74178b74c2ae9b2014fd6effe25fec5ff88d30a2",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_fe4c8",
                    table="rudicatalogos_areaexperiencia",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="areaexperiencia",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "rudicatalogos_areaexperiencia" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="97e7b783067f9a8f8bf237d919ca01d5d46bd0d3",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_9edd6",
                    table="rudicatalogos_areaexperiencia",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="areaexperiencia",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_parametro_readonly_codigo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."codigo" IS DISTINCT FROM (NEW."codigo"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="195979eced5df57e886e6ba45a6a3b603d586093",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_parametro_readonly_codigo_7e3f6",
                    table="rudicatalogos_areaexperiencia",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="departamento",
            index=models.Index(
                fields=["created_at"], name="idx_departamento_createdat"
            ),
        ),
        migrations.AddIndex(
            model_name="departamento",
            index=models.Index(
                fields=["updated_at"], name="idx_departamento_updatedat"
            ),
        ),
        migrations.AddConstraint(
            model_name="departamento",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nombre"),
                name="unq_departamento_nombre",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="departamento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="f95650c570fd5eadeef43469950d35523d789661",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_77b8c",
                    table="rudicatalogos_departamento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="departamento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="5a0344b728538132a7cf52e266fc923a4f3c3796",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_3fe49",
                    table="rudicatalogos_departamento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="departamento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="0157a852aed3dc03e73f755dd98f773a1c020a7a",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_4e80f",
                    table="rudicatalogos_departamento",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="departamento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete or update rows from % table', TG_TABLE_NAME;",
                    hash="15c081e9d9bf690d4803458cc4fa123754fb2190",
                    operation="DELETE OR UPDATE",
                    pgid="pgtrigger_trg_append_only_e99a2",
                    table="rudicatalogos_departamento",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="motivo",
            index=models.Index(fields=["created_at"], name="idx_motivo_createdat"),
        ),
        migrations.AddIndex(
            model_name="motivo",
            index=models.Index(fields=["updated_at"], name="idx_motivo_updatedat"),
        ),
        migrations.AddConstraint(
            model_name="motivo",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "codigo__regex",
                    "^[\\p{L}\\d_-]+(\\.[\\p{L}\\d_-]+)*$",
                )),
                name="chk_motivo_codigo_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="motivo",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                name="unq_motivo_codigo",
            ),
        ),
        migrations.AddConstraint(
            model_name="motivo",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "ambito__in",
                    [
                        "anulacion_constancia",
                        "anulacion_participacion",
                        "cancelacion_actividad",
                        "cancelacion_inscripcion",
                        "fusion_usuario",
                        "rechazo_mentoria",
                        "rechazo_importacion",
                        "revocar_consentimiento",
                    ],
                )),
                name="chk_motivo_ambito",
            ),
        ),
        migrations.AddConstraint(
            model_name="motivo",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "visibilidad__in",
                    ["administracion", "publico", "participante"],
                )),
                name="chk_motivo_visibilidad",
            ),
        ),
        migrations.AddConstraint(
            model_name="motivo",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                django.db.models.functions.text.Lower("ambito"),
                name="unq_motivo_ambito",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="motivo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="b96c57fd933b20e9d9723ded663a91d41be69029",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_d72f0",
                    table="rudicatalogos_motivo",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="motivo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="6285e1479c9921adb728027403a6e0cc10362bb4",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_a39c3",
                    table="rudicatalogos_motivo",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="motivo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="0971a609f623d2f49228fd95ebdb2220a3ba39f0",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_0a097",
                    table="rudicatalogos_motivo",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="motivo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "rudicatalogos_motivo" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="2a89f624813bf490e788193e53289af62dbcaf6d",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_8d079",
                    table="rudicatalogos_motivo",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="motivo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_parametro_readonly_codigo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."codigo" IS DISTINCT FROM (NEW."codigo"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="54615b88f788a97319d93054259a11b2a439ed96",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_parametro_readonly_codigo_d940a",
                    table="rudicatalogos_motivo",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="municipios",
                to="rudicatalogos.departamento",
            ),
        ),
        migrations.AddField(
            model_name="parametro",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="parametros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="plantillamensaje",
            index=models.Index(
                fields=["created_at"], name="idx_plantillamensaje_createdat"
            ),
        ),
        migrations.AddIndex(
            model_name="plantillamensaje",
            index=models.Index(
                fields=["updated_at"], name="idx_plantillamensaje_updatedat"
            ),
        ),
        migrations.AddConstraint(
            model_name="plantillamensaje",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "codigo__regex",
                    "^[\\p{L}\\d_-]+(\\.[\\p{L}\\d_-]+)*$",
                )),
                name="chk_plantillamensaje_codigo_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantillamensaje",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                name="unq_plantillamensaje_codigo",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantillamensaje",
            constraint=models.CheckConstraint(
                condition=django.db.models.expressions.RawSQL(
                    output_field=models.BooleanField(),
                    params=(),
                    sql="jsonb_typeof(variables) = 'array'",
                ),
                name="chk_plantillamensaje_variables",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantillamensaje",
            constraint=models.CheckConstraint(
                condition=models.Q(("cuerpo__len__gte", 1), ("cuerpo__len__lte", 8000)),
                name="chk_plantillamensaje_cuerpo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plantillamensaje",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="815dd039faa8b2d324330f81be1c4962bc20b985",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_eff5f",
                    table="rudicatalogos_plantillamensaje",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plantillamensaje",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="e26863eb8ae85c88ef7e589263572ea4e2fb4491",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_9baae",
                    table="rudicatalogos_plantillamensaje",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plantillamensaje",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="f2f60a3baa05b6fc6995ad1e0184e0453321594a",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_abb38",
                    table="rudicatalogos_plantillamensaje",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plantillamensaje",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "rudicatalogos_plantillamensaje" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="aabc964507bf9c0f5df47143d00741a05ad5366d",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_020ac",
                    table="rudicatalogos_plantillamensaje",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plantillamensaje",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_parametro_readonly_codigo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."codigo" IS DISTINCT FROM (NEW."codigo"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c4effd60a58ca739f261e25c6c7dabd2866961f0",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_parametro_readonly_codigo_1a07d",
                    table="rudicatalogos_plantillamensaje",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plantillamensaje",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_plantillamensaje_variables_insert_integrity",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="DECLARE campo text; texto text; BEGIN IF EXISTS ( SELECT 1 FROM jsonb_array_elements_text(NEW.variables) AS elem WHERE NEW.asunto NOT LIKE '%{' || elem || '}%' AND NEW.cuerpo NOT LIKE '%{' || elem || '}%' ) THEN RAISE check_violation USING COLUMN = 'variables', MESSAGE = 'Una de las variables especificadas no está presente en el asunto o el cuerpo de la plantilla.'; END IF; FOR campo, texto IN VALUES ('asunto', NEW.asunto), ('cuerpo', NEW.cuerpo) LOOP IF EXISTS ( SELECT 1 FROM regexp_matches(texto, '\\{([^}]+)\\}', 'g') AS match(m) WHERE NOT (NEW.variables ? match.m[1]) ) THEN RAISE check_violation USING COLUMN = campo, MESSAGE = format('Uno de los parámetros especificados en el %s no tiene una variable correspondiente.', campo); END IF; END LOOP; RETURN NEW; END;",
                    hash="0c24c6b7208e6ac5a92d9146fee81bb98feaa5b1",
                    operation="INSERT",
                    pgid="pgtrigger_trg_plantillamensaje_variables_insert_integrity_70536",
                    table="rudicatalogos_plantillamensaje",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plantillamensaje",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_plantillamensaje_variables_update_integrity",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."asunto" IS DISTINCT FROM (NEW."asunto") OR OLD."cuerpo" IS DISTINCT FROM (NEW."cuerpo") OR OLD."variables" IS DISTINCT FROM (NEW."variables"))',
                    func="DECLARE campo text; texto text; BEGIN IF EXISTS ( SELECT 1 FROM jsonb_array_elements_text(NEW.variables) AS elem WHERE NEW.asunto NOT LIKE '%{' || elem || '}%' AND NEW.cuerpo NOT LIKE '%{' || elem || '}%' ) THEN RAISE check_violation USING COLUMN = 'variables', MESSAGE = 'Una de las variables especificadas no está presente en el asunto o el cuerpo de la plantilla.'; END IF; FOR campo, texto IN VALUES ('asunto', NEW.asunto), ('cuerpo', NEW.cuerpo) LOOP IF EXISTS ( SELECT 1 FROM regexp_matches(texto, '\\{([^}]+)\\}', 'g') AS match(m) WHERE NOT (NEW.variables ? match.m[1]) ) THEN RAISE check_violation USING COLUMN = campo, MESSAGE = format('Uno de los parámetros especificados en el %s no tiene una variable correspondiente.', campo); END IF; END LOOP; RETURN NEW; END;",
                    hash="8e3f18482997f3deab9c250248d9d4419a79343e",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_plantillamensaje_variables_update_integrity_702de",
                    table="rudicatalogos_plantillamensaje",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="rolparticipacion",
            index=models.Index(
                fields=["created_at"], name="idx_rolparticipacion_createdat"
            ),
        ),
        migrations.AddIndex(
            model_name="rolparticipacion",
            index=models.Index(
                fields=["updated_at"], name="idx_rolparticipacion_updatedat"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolparticipacion",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "codigo__regex",
                    "^[\\p{L}\\d_-]+(\\.[\\p{L}\\d_-]+)*$",
                )),
                name="chk_rolparticipacion_codigo_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolparticipacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("descripcion__len__lte", 300)),
                name="chk_rolparticipacion_descripcion",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolparticipacion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                name="unq_rolparticipacion_codigo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rolparticipacion",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="06da5f475f27684894ba3910e7f8c66260cfa3d8",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_e97ef",
                    table="rudicatalogos_rolparticipacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rolparticipacion",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="b9b85d017673a29f8570942f12db3ede99c7bbc1",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_f3247",
                    table="rudicatalogos_rolparticipacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rolparticipacion",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="a99691128d5b08fc6a97b559393aaa394b64018d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_d1815",
                    table="rudicatalogos_rolparticipacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rolparticipacion",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "rudicatalogos_rolparticipacion" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="68198bf5b06f2093e6c92acd383533e7d4b684cc",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_b1e5b",
                    table="rudicatalogos_rolparticipacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="rolparticipacion",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_parametro_readonly_codigo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."codigo" IS DISTINCT FROM (NEW."codigo"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="23a213b6a29a657c262e8195d6e78aa942329177",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_parametro_readonly_codigo_cfb99",
                    table="rudicatalogos_rolparticipacion",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="tipoactividad",
            index=models.Index(
                fields=["created_at"], name="idx_tipoactividad_createdat"
            ),
        ),
        migrations.AddIndex(
            model_name="tipoactividad",
            index=models.Index(
                fields=["updated_at"], name="idx_tipoactividad_updatedat"
            ),
        ),
        migrations.AddConstraint(
            model_name="tipoactividad",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "codigo__regex",
                    "^[\\p{L}\\d_-]+(\\.[\\p{L}\\d_-]+)*$",
                )),
                name="chk_tipoactividad_codigo_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipoactividad",
            constraint=models.CheckConstraint(
                condition=models.Q(("descripcion__len__lte", 300)),
                name="chk_tipoactividad_descripcion",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipoactividad",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                name="unq_tipoactividad_codigo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipoactividad",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="188c9150c1541558d6f798d278877b8d98c65503",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_73e40",
                    table="rudicatalogos_tipoactividad",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipoactividad",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="a0868e00ea06a66746418b5e629dff50ae82bcc6",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_70ecf",
                    table="rudicatalogos_tipoactividad",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipoactividad",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="7a1871e70a596fe288f350488b2e7b5d897858a1",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_ad8cc",
                    table="rudicatalogos_tipoactividad",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipoactividad",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "rudicatalogos_tipoactividad" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="f582bd32c48e135e497ccd20b9f2089d64d01b94",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_7c34f",
                    table="rudicatalogos_tipoactividad",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipoactividad",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_parametro_readonly_codigo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."codigo" IS DISTINCT FROM (NEW."codigo"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="67e620bc4cb31998b9b05a9629abb319f94a0829",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_parametro_readonly_codigo_d2090",
                    table="rudicatalogos_tipoactividad",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="tipomentor",
            index=models.Index(fields=["created_at"], name="idx_tipomentor_createdat"),
        ),
        migrations.AddIndex(
            model_name="tipomentor",
            index=models.Index(fields=["updated_at"], name="idx_tipomentor_updatedat"),
        ),
        migrations.AddConstraint(
            model_name="tipomentor",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "codigo__regex",
                    "^[\\p{L}\\d_-]+(\\.[\\p{L}\\d_-]+)*$",
                )),
                name="chk_tipomentor_codigo_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipomentor",
            constraint=models.CheckConstraint(
                condition=models.Q(("descripcion__len__lte", 300)),
                name="chk_tipomentor_descripcion",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipomentor",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                name="unq_tipomentor_codigo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipomentor",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="ea7a3288e92b4e072b11c5a169c2d3564d57cedd",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_d6a92",
                    table="rudicatalogos_tipomentor",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipomentor",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="5776a7c1853ae1b4a9cd7080ff63398aba497a91",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_51684",
                    table="rudicatalogos_tipomentor",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipomentor",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="8d3cfb3b62bba5eb4df55539c0411300d842ca1a",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_d7168",
                    table="rudicatalogos_tipomentor",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipomentor",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "rudicatalogos_tipomentor" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="303c009c24f1b07e91adc68bd40dbdaed7f11228",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_6e022",
                    table="rudicatalogos_tipomentor",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tipomentor",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_parametro_readonly_codigo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."codigo" IS DISTINCT FROM (NEW."codigo"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="b5f906aba2999dd9e8c0e046853399459a8c6fdc",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_parametro_readonly_codigo_e2fc6",
                    table="rudicatalogos_tipomentor",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="tiporeconocimiento",
            index=models.Index(
                fields=["created_at"], name="idx_tiporeconocimiento_createdat"
            ),
        ),
        migrations.AddIndex(
            model_name="tiporeconocimiento",
            index=models.Index(
                fields=["updated_at"], name="idx_tiporeconocimiento_updatedat"
            ),
        ),
        migrations.AddConstraint(
            model_name="tiporeconocimiento",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "codigo__regex",
                    "^[\\p{L}\\d_-]+(\\.[\\p{L}\\d_-]+)*$",
                )),
                name="chk_tiporeconocimiento_codigo_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="tiporeconocimiento",
            constraint=models.CheckConstraint(
                condition=models.Q(("descripcion__len__lte", 300)),
                name="chk_tiporeconocimiento_descripcion",
            ),
        ),
        migrations.AddConstraint(
            model_name="tiporeconocimiento",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                name="unq_tiporeconocimiento_codigo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tiporeconocimiento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="375c5e87566f94f4a098c11096d812efd31c440e",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_c2eb8",
                    table="rudicatalogos_tiporeconocimiento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tiporeconocimiento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="1fcb2b984280636e0e6dc8283417c35cd27dfa39",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_9fcf2",
                    table="rudicatalogos_tiporeconocimiento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tiporeconocimiento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="3171ade1ad925b698fcf42e20ebb373413f35781",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_8c0dd",
                    table="rudicatalogos_tiporeconocimiento",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tiporeconocimiento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "rudicatalogos_tiporeconocimiento" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="fb42aa4d6760b441aa3c5bba6f6ae8e2de3d9175",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_504a9",
                    table="rudicatalogos_tiporeconocimiento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tiporeconocimiento",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_parametro_readonly_codigo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."codigo" IS DISTINCT FROM (NEW."codigo"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="07ac82f1e3b2be6a71c1420e1e36d4fa1289ff0b",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_parametro_readonly_codigo_6e09a",
                    table="rudicatalogos_tiporeconocimiento",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="municipio",
            index=models.Index(fields=["created_at"], name="idx_municipio_createdat"),
        ),
        migrations.AddIndex(
            model_name="municipio",
            index=models.Index(fields=["updated_at"], name="idx_municipio_updatedat"),
        ),
        migrations.AddConstraint(
            model_name="municipio",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nombre"),
                name="unq_municipio_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="municipio",
            constraint=models.UniqueConstraint(
                models.F("departamento"),
                django.db.models.functions.text.Lower("nombre"),
                name="unq_municipio_nombre_departamento",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipio",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="f81ed0752a8a52010227119689374f28dde8ed87",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_e029c",
                    table="rudicatalogos_municipio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipio",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="cbc9e15912be531ee288520e616f06d317b55ed8",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_928e2",
                    table="rudicatalogos_municipio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipio",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="9803d6dd3ac0fb129319a902e938d70f22baf0fc",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_5b153",
                    table="rudicatalogos_municipio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipio",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete or update rows from % table', TG_TABLE_NAME;",
                    hash="1d738ca2167da0ad22213b23eed836ca16ba636a",
                    operation="DELETE OR UPDATE",
                    pgid="pgtrigger_trg_append_only_0cbb8",
                    table="rudicatalogos_municipio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="parametro",
            index=models.Index(fields=["created_at"], name="idx_parametro_createdat"),
        ),
        migrations.AddIndex(
            model_name="parametro",
            index=models.Index(fields=["updated_at"], name="idx_parametro_updatedat"),
        ),
        migrations.AddConstraint(
            model_name="parametro",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "codigo__regex",
                    "^[\\p{L}\\d_-]+(\\.[\\p{L}\\d_-]+)*$",
                )),
                name="chk_parametro_codigo_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametro",
            constraint=models.CheckConstraint(
                condition=models.Q(("descripcion__len__lte", 300)),
                name="chk_parametro_descripcion",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametro",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                name="unq_parametro_codigo",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametro",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "grupo__in",
                    ["registro", "sesion", "inscripcion", "vigencia", "importacion"],
                )),
                name="chk_parametro_grupo",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametro",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "tipo__in",
                    ["binario", "entero", "lista", "texto", "duracion"],
                )),
                name="chk_parametro_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="parametro",
            constraint=models.CheckConstraint(
                condition=django.db.models.expressions.RawSQL(
                    output_field=models.BooleanField(),
                    params=(),
                    sql="jsonb_typeof(restricciones) = 'object'",
                ),
                name="chk_parametro_restricciones",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="parametro",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="d3565f66fb037e78da08c0d673d0aa7b7aae1e20",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_2ae58",
                    table="rudicatalogos_parametro",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="parametro",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="feeef068e81e12b290cf8f4b88895989bb8a5b0c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_dc984",
                    table="rudicatalogos_parametro",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="parametro",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="cadd9205b43c3aed1fef69e41ac281b29087b75b",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_5aa04",
                    table="rudicatalogos_parametro",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="parametro",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "rudicatalogos_parametro" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="ae48e819be7fe93ae2c9c821cc5ca07bd64d4f87",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_7e0eb",
                    table="rudicatalogos_parametro",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="parametro",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_parametro_readonly_codigo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."codigo" IS DISTINCT FROM (NEW."codigo"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="20561742486eacfb088e913c1e4c384a846b7e8a",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_parametro_readonly_codigo_4c451",
                    table="rudicatalogos_parametro",
                    when="BEFORE",
                ),
            ),
        ),
    ]
