name: "setup-services"

runs:
  using: "composite"
  steps:
    - name: start services
      shell: bash
      run: docker compose up --detach --wait postgres redis

    - name: export service env
      shell: bash
      run: |
        {
          echo "DATABASE_URL=postgresql://rudiapi:rudiapi@127.0.0.1:5432/rudiapi"
          echo "REDIS_SECRET_KEY=rudiapi"
          echo "REDIS_URL=redis://127.0.0.1:6379"
        } >> "$GITHUB_ENV"
