name: validate

on:
  push:
    branches-ignore:
      - "chore/deps"
      - "dependabot/**"
      - "**docs**"
    paths: &validate-paths
      - "src/**"
      - "compose.yml"
      - "pyproject.toml"
      - "uv.lock"
      - ".python-version"
      - ".github/actions/setup-django-env/action.yml"
      - ".github/actions/setup-services/action.yml"
      - ".github/actions/setup-tools/action.yml"
      - ".github/workflows/validate.yml"
  pull_request:
    paths: *validate-paths
  workflow_dispatch:

concurrency:
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

permissions:
  contents: read

jobs:
  validate-rudiapi:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: setup tools
        uses: ./.github/actions/setup-tools

      - name: setup django env
        uses: ./.github/actions/setup-django-env

      - name: setup services
        uses: ./.github/actions/setup-services

      - name: run system checks
        run: uv run --frozen src/manage.py check --deploy --fail-level WARNING
